import { Roboto } from 'next/font/google';
import "../styles/globals.scss";
import Header from '../components/layout/header/Header';

export const roboto = Roboto({subsets: ['cyrillic', 'latin'], weight: ['500', '700']});

export const metadata = {
  title: "Track Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
